name: Trigger Webhook

on:
  schedule:
    # Runs every 2 minutes
    - cron: "*/2 * * * *"
 
  # Optional: allow manual run from GitHub UI
  workflow_dispatch:

jobs:
  call-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook
        run: |
          curl -X GET "https://unsparse-sherman-nonfallaciously.ngrok-free.dev/webhook/health"
